from php:apache

RUN apt-get -y update && apt-get -y upgrade

#RUN apt-get install php7.2-pgsql 

#RUN apk add --update \
#apache2-proxy \
#apache2-proxy-html 

#RUN apk add --update \
#vim \
#apache2 \
#php7 \
#php7-apache2 \
#php7-fpm \
#php7-pdo \
#php7-pdo_pgsql \
#php7-mcrypt \
#php7-mbstring \
#php7-xml \
#php7-xmlwriter \
#php7-openssl \
#php7-json \
#php7-phar \
#php7-zip \
#php7-dom \
#php7-session \
#php7-tokenizer \
#php7-opcache \
#php7-zlib && \
#php7 -r "copy('http://getcomposer.org/installer', 'composer-setup.php');" && \
#php7 composer-setup.php --install-dir=/usr/bin --filename=composer && \
#php7 -r "unlink('composer-setup.php');" && \
#ln -s /etc/php7/php.ini /etc/php7/conf.d/php.ini

#RUN apk add --update \
#bash \
#openssh-client 

RUN php -m
#RUN composer global require "laravel/installer"
#RUN composer create-project --prefer-dist laravel/laravel dbs

#RUN sed -ri -e 's!/usr/local/apache2/htdocs!/usr/local/apache2/dbs!g' /usr/local/apache2/conf/*.conf

#WORKDIR /usr/local/apache2/dbs

#RUN ls -l /usr/local/apache2/modules/