version: "3.5"

networks:
  dbs-network:
    name: dbs-network
    driver: bridge

services:
  dbs-db:
    image: postgres:13-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-db
    ports: 
      - "5432:5432"
    networks: 
      - dbs-network
    volumes:
      - ./db_post_create_scripts:/docker-entrypoint-initdb.d
      - /var/lib/docker/volumes/dbs_db:/var/lib/postgresql/data/pgdata
    environment:
      - DEBUG=false
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=dbs_user
      - POSTGRES_PASSWORD=dbs_password
      - POSTGRES_DB=dbs_db

  dbs-core:
    image: tomdale55/dbs-core
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-core
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
    volumes:
#      - /root/dbs/code/dbs/app/User.php:/var/www/html/dbs/app/User.php
#      - ./dbs_test_dot_env:/var/www/html/dbs/.env
#      - /root/dbs/code/dbs/app/support_files/wait_for_db_then_migrate.php:/var/www/html/dbs/wait_for_db_then_migrate.php
#      - /root/dbs/code/dbs/public/index.php:/var/www/html/dbs/public/index.php
      - /root/dbs/code/dbs/routes:/var/www/html/dbs/routes
#      - /root/dbs/code/dbs/resources:/var/www/html/dbs/resources
      - /root/dbs/code/dbs/database/migrations:/var/www/html/dbs/database/migrations
#      - /root/dbs/code/dbs/app/Classes:/var/www/html/dbs/app/Classes
      - /root/dbs/code/dbs/app/sql:/var/www/html/dbs/app/sql
      - /root/dbs/code/dbs/app/Http/Controllers:/var/www/html/dbs/app/Http/Controllers
#      - /root/dbs/code/dbs/app/Console/Kernel.php:/var/www/html/dbs/app/Console/Kernel.php
#      - /root/dbs/logs/core:/var/www/html/dbs/storage/logs

  dbs-snapper:
    image: tomdale55/dbs-snapper
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-snapper
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
      - dbs-core
    entrypoint: /opt/dbs-snapper/dbs.php  
    volumes:
      #- /root/dbs/code/dbs_snapper/.app_key.txt:/opt/dbs-snapper/.app_key.txt
      #- /root/dbs/code/dbs_snapper/.repo_pw.txt:/opt/dbs-snapper/.repo_pw.txt
      - /root/dbs/code/dbs_snapper:/opt/dbs-snapper
      - /root/dbs/logs/agent:/var/log/dbs-snapper   
    environment:
      - DBS_LOGGING=true
      - APP_KEY=XHMx1P9OlMbexRKExMF4k8qXmIvonudg
      - REPO_PW=dbs_password

  dbs-web:
    image: tomdale55/dbs-web
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-web
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
      - dbs-core
    ports:
      - "80:80"
      - "443:443"
    working_dir: /var/www/html/dbs/public
    volumes:
      - ./certs:/etc/nginx/certs
#      - ./site.conf:/etc/nginx/conf.d/site.conf
#      - /root/dbs/code/dbs/public/index.html:/var/www/html/dbs/public/index.html
#      - /root/dbs/code/dbs/public/css:/var/www/html/dbs/public/css
      - /root/dbs/code/dbs/public/js:/var/www/html/dbs/public/js
#      - /root/dbs/code/dbs/public/assets:/var/www/html/dbs/public/assets
#      - /root/dbs/code/dbs/public/plugs:/var/www/html/dbs/public/plugs
#      - /root/dbs/code/dbs/public/fonts:/var/www/html/dbs/public/fonts
#      - /root/dbs/code/dbs/public/favicon.ico:/var/www/html/dbs/public/favicon.ico
#      - /root/dbs/logs/web:/var/log/nginx





