version: "3.5"

networks:
  dbs-network:
    name: dbs-network
    driver: bridge

services:
  dbs-db:
    image: postgres:11-alpine
    container_name: dbs-db
    ports: 
      - "5432:5432"
    networks: 
      - dbs-network
    volumes:
      - ./db_post_create_scripts:/docker-entrypoint-initdb.d
      - /var/lib/docker/volumes/dbs_db:/var/lib/postgresql/data/pgdata
    environment:
      - DEBUG=false
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=dbs_user
      - POSTGRES_PASSWORD=dbs_password
      - POSTGRES_DB=dbs_db

  dbs-core:
    image: tomdale55/dbs-core
    container_name: dbs-core
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
    volumes:
      - ./dbs_test_dot_env:/var/www/html/dbs/.env
      - /root/dbs/code/dbs/public/index.php:/var/www/html/dbs/public/index.php
      - /root/dbs/code/dbs/routes:/var/www/html/dbs/routes
      - /root/dbs/code/dbs/resources:/var/www/html/dbs/resources
      - /root/dbs/code/dbs/database/migrations:/var/www/html/dbs/database/migrations
      - /root/dbs/code/dbs/app/Classes:/var/www/html/dbs/app/Classes
      - /root/dbs/code/dbs/app/sql:/var/www/html/dbs/app/sql
      - /root/dbs/code/dbs/app/Http/Controllers:/var/www/html/dbs/app/Http/Controllers
      - /root/dbs/code/dbs/app/Console/Kernel.php:/var/www/html/dbs/app/Console/Kernel.php

  dbs-snapper:
    image: tomdale55/dbs-snapper
    container_name: dbs-snapper
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
      - dbs-core
    volumes:
      - ./sqlnet.ora:/usr/lib/oracle/18.3/client64/lib/network/admin/sqlnet.ora
      - /root/dbs/code/dbs_snapper:/opt/dbs-snapper
      - /root/dbs/logs:/var/log/dbs-snapper
    entrypoint: /opt/dbs-snapper/dbs.php     

  dbs-web:
    image: nginx:alpine
    container_name: dbs-web
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
      - dbs-core
    ports:
      - "80:80"
    working_dir: /var/www/html/dbs/public
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - /root/dbs/code/dbs/public/index.html:/var/www/html/dbs/public/index.html
      - /root/dbs/code/dbs/public/css:/var/www/html/dbs/public/css
      - /root/dbs/code/dbs/public/js:/var/www/html/dbs/public/js
      - /root/dbs/code/dbs/public/assets:/var/www/html/dbs/public/assets
      - /root/dbs/code/dbs/public/plugs:/var/www/html/dbs/public/plugs
      - /root/dbs/code/dbs/public/fonts:/var/www/html/dbs/public/fonts
      - /root/dbs/code/dbs/public/favicon.ico:/var/www/html/dbs/public/favicon.ico




