version: "3.5"

networks:
  dbs-network:
    name: dbs-network
    driver: bridge

services:
  dbs-db:
    image: tomdale55/dbs-db
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-db
    ports: 
      - "5432:5432"
    networks: 
      - dbs-network
    volumes:
      #- ./db_post_create_scripts:/docker-entrypoint-initdb.d
      - /var/lib/docker/volumes/dbs_db:/var/lib/postgresql/data/pgdata
    environment:
      - DEBUG=false
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=dbs_user
      - POSTGRES_PASSWORD=dbs_password
      - POSTGRES_DB=dbs_db

  dbs-core:
    image: tomdale55/dbs-core
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-core
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
    volumes:
      - /root/dbs/logs:/var/www/html/dbs/storage/logs
      - /root/dbs/process-snaps:/var/www/html/dbs/storage/app/process-snaps
      - /root/dbs/perf-snaps:/var/www/html/dbs/storage/app/perf-snaps

  dbs-snapper:
    image: tomdale55/dbs-snapper
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-snapper
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
      - dbs-core
    entrypoint: /opt/dbs-snapper/dbs.php  
    volumes:
      - /root/dbs/logs:/var/log/dbs-snapper 
      - /root/dbs/process-snaps:/opt/dbs-snapper/process-snaps  
    environment:
      - DBS_LOGGING=true
      - APP_KEY=XHMx1P9OlMbexRKExMF4k8qXmIvonudg
      - REPO_PW=SaLpoECIiEmSNgC6hFPKHw==

  dbs-web:
    image: tomdale55/dbs-web
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-web
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
      - dbs-core
    ports:
      - "80:80"
      - "443:443"
    working_dir: /var/www/html/dbs/public
    volumes:
    #  - ./certs:/etc/nginx/certs
      - /root/dbs/logs:/var/log/nginx





