version: "3.5"

networks:
  dbs-network:
    name: dbs-network
    driver: bridge

services:
  dbs-db:
    image: tomdale55/dbs-db
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-db
    ports: 
      - "5432:5432"
    networks: 
      - dbs-network
    volumes:
      - /home/dbs/db:/var/lib/postgresql/data/pgdata
    environment:
      - DEBUG=false
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=dbs_user
      - POSTGRES_PASSWORD=dbs_password
      - POSTGRES_DB=dbs_db

  dbs-core:
    image: tomdale55/dbs-core
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-core
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
    volumes:
      - /home/dbs/code/dbs/routes:/var/www/html/dbs/routes
      - /home/dbs/code/dbs/resources:/var/www/html/dbs/resources
      - /home/dbs/code/dbs/database/migrations:/var/www/html/dbs/database/migrations
      - /home/dbs/code/dbs/app/Classes:/var/www/html/dbs/app/Classes
      - /home/dbs/code/dbs/app/sql:/var/www/html/dbs/app/sql
      - /home/dbs/code/dbs/app/Http/Controllers:/var/www/html/dbs/app/Http/Controllers
      - /home/dbs/code/dbs/app/Console/Kernel.php:/var/www/html/dbs/app/Console/Kernel.php
      - /home/dbs/code/dbs/app/Notifications:/var/www/html/dbs/app/Notifications
      - /home/dbs/logs:/var/www/html/dbs/storage/logs
      - /home/dbs/process-snaps:/var/www/html/dbs/storage/app/process-snaps
      - /home/dbs/perf-snaps:/var/www/html/dbs/storage/app/perf-snaps

  dbs-snapper:
    image: tomdale55/dbs-snapper
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-snapper
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
      - dbs-core
    entrypoint: /opt/dbs-snapper/dbs.php  
    volumes:
      - /home/dbs/code/dbs_snapper:/opt/dbs-snapper
      - /home/dbs/process-snaps:/opt/dbs-snapper/process-snaps  
      - /home/dbs/logs:/var/log/dbs-snapper   
    environment:
      - DBS_LOGGING=true
      - APP_KEY=XHMx1P9OlMbexRKExMF4k8qXmIvonudg
      - REPO_PW=SaLpoECIiEmSNgC6hFPKHw==

  dbs-web:
    image: tomdale55/dbs-web
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    container_name: dbs-web
    networks: 
      - dbs-network
    depends_on: 
      - dbs-db
      - dbs-core
    ports:
      - "80:80"
      - "443:443"
    working_dir: /var/www/html/dbs/public
    volumes:
      - ./certs:/etc/nginx/certs
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - /home/dbs/code/dbs/public/index.html:/var/www/html/dbs/public/index.html
      - /home/dbs/code/dbs/public/css:/var/www/html/dbs/public/css
      - /home/dbs/code/dbs/public/js:/var/www/html/dbs/public/js
      - /home/dbs/code/dbs/public/assets:/var/www/html/dbs/public/assets
      - /home/dbs/code/dbs/public/plugs:/var/www/html/dbs/public/plugs
      - /home/dbs/code/dbs/public/fonts:/var/www/html/dbs/public/fonts
      - /home/dbs/code/dbs/public/favicon.ico:/var/www/html/dbs/public/favicon.ico
      - /home/dbs/code/dbs/public/softwerks:/var/www/html/dbs/public/softwerks
      - /home/dbs/logs:/var/log/nginx





